export const DISTRICTS = [
  // Provincia de Lima
  'Ancón, Lima Metropolitana, Perú',
  'Ate, Lima, Perú',
  'Barranco, Lima, Perú',
  'Breña, Lima, Perú',
  'Carabayllo, Lima, Perú',
  'Chaclacayo, Lima, Perú',
  'Chorrillos, Lima, Perú',
  'Cieneguilla, Lima, Perú',
  'Comas, Lima, Perú',
  'El Agustino, Lima, Perú',
  'Independencia, Lima, Perú',
  'Jesús María, Lima, Perú',
  'La Molina, Lima, Perú',
  'La Victoria, Lima, Perú',
  'Lima, Lima, Perú',
  'Lince, Lima, Perú',
  'Los Olivos, Lima, Perú',
  'Lurigancho, Lima, Perú',
  'Lurín, Lima, Perú',
  'Magdalena del Mar, Lima, Perú',
  'Miraflores, Lima, Perú',
  'Pachacámac, Lima, Perú',
  'Pucusana, Lima, Perú',
  'Pueblo Libre, Lima, Perú',
  'Puente Piedra, Lima, Perú',
  'Punta Hermosa, Lima, Perú',
  'Punta Negra, Lima, Perú',
  'Rímac, Lima, Perú',
  'San Bartolo, Lima, Perú',
  'San Borja, Lima, Perú',
  'San Isidro, Lima, Perú',
  'San Juan de Lurigancho, Lima, Perú',
  'San Juan de Miraflores, Lima, Perú',
  'San Luis, Lima, Perú',
  'San Martín de Porres, Lima, Perú',
  'San Miguel, Lima, Perú',
  'Santa Anita, Lima, Perú',
  'Santa María del Mar, Lima, Perú',
  'Santa Rosa, Lima, Perú',
  'Santiago de Surco, Lima, Perú',
  'Surquillo, Lima, Perú',
  'Villa El Salvador, Lima, Perú',
  'Villa María del Triunfo, Lima, Perú',

  // Provincia Constitucional del Callao
  'Bellavista, Callao, Perú',
  'Callao, Callao, Perú',
  'Carmen de la Legua-Reynoso, Callao, Perú',
  'La Perla, Callao, Perú',
  'Ventanilla, Callao, Perú'
]
