export const DISTRICTS = {
  ANCON: 'Ancon',
  ATE: 'Ate',
  BARRANCO: 'Barranco',
  BRENA: 'Breña',
  CARABAYLLO: 'Carabayllo',
  CHACLACAYO: 'Chaclacayo',
  CHORRILLOS: 'Chorrillos',
  CIENEGUILLA: 'Cieneguilla',
  COMAS: 'Comas',
  EL_AGUSTINO: 'El Agustino',
  INDEPENDENCIA: 'Independencia',
  JESUS_MARIA: 'Jesus Maria',
  LA_MOLINA: 'La Molina',
  LA_VICTORIA: 'La Victoria',
  LIMA: 'Lima',
  LINCE: 'Lince',
  LOS_OLIVOS: 'Los Olivos',
  LURIGANCHO: 'Lurigancho',
  LURIN: 'Lurin',
  MAGDALENA_DEL_MAR: 'Magdalena del Mar',
  MIRAFLORES: 'Miraflores',
  PACHACAMAC: 'Pachacamac',
  PUCUSANA: 'Pucusana',
  PUEBLO_LIBRE: 'Pueblo Libre',
  PUENTE_PIEDRA: 'Puente Piedra',
  PUNTA_HERMOSA: 'Punta Hermosa',
  PUNTA_NEGRA: 'Punta Negra',
  RIMAC: 'Rimac',
  SAN_BARTOLO: 'San Bartolo',
  SAN_BORJA: 'San Borja',
  SAN_ISIDRO: 'San Isidro',
  SAN_JUAN_DE_LURIGANCHO: 'San Juan de Lurigancho',
  SAN_JUAN_DE_MIRAFLORES: 'San Juan de Miraflores',
  SAN_LUIS: 'San Luis',
  SAN_MARTIN_DE_PORRES: 'San Martin de Porres',
  SAN_MIGUEL: 'San Miguel',
  SANTA_ANITA: 'Santa Anita',
  SANTA_MARIA_DEL_MAR: 'Santa Maria del Mar',
  SANTA_ROSA: 'Santa Rosa',
  SANTIAGO_DE_SURCO: 'Santiago de Surco',
  SURQUILLO: 'Surquillo',
  VILLA_EL_SALVADOR: 'Villa El Salvador',
  VILLA_MARIA_DEL_TRIUNFO: 'Villa Maria del Triunfo'
}
