sequenceDiagram
    actor U as Usuario
    participant S as Sistema
    actor A as Arrendador
    participant P as Pasarela de Pago

  

    U->>S: Buscar garages (ubicación, precio, tipo)
    S-->>U: Lista de garages disponibles

  

    U->>S: Crear solicitud de reserva (mes/día/hora)
    S->>S: Calcular precio + comisión
    S-->>U: Reserva creada (estado: Pendiente)

  

    S->>A: Notificar nueva solicitud
    A-->>S: Aceptar/Rechazar

  

    alt Rechazado
        S-->>U: Estado = Rechazado
    else Aceptado
        S-->>U: Estado = Aceptado (sin pagar)
        U->>S: Iniciar pago
        S->>P: Procesar pago
        P-->>S: Confirmación de pago

  

        alt Pago exitoso
            S-->>U: Estado = Pagado
            S-->>U: Acceso al garage según modalidad

        else Pago fallido
            S-->>U: Estado = Aceptado (sin pagar)
        end
    end